repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Run custom scripts before committing
  - repo: local
    hooks:
      - id: code-quality-check
        name: Code quality check (isort, black, pylint)
        entry: python
        args: [check_code_quality.py]
        language: system
        pass_filenames: false
        always_run: true

      - id: run-tests
        name: Run all tests
        entry: python
        args: [run_tests.py]
        language: system
        pass_filenames: false
        always_run: true