services:
  postgres:
    image: postgres:15
    container_name: prefect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prefect-server:
    image: prefecthq/prefect:2.20-python3.10
    container_name: prefect-server
    depends_on:
      - postgres
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    command: >
      prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./prefect:/root/.prefect

  prefect-worker:
    image: prefecthq/prefect:2.20-python3.10
    container_name: prefect-worker
    depends_on:
      - prefect-server
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    command: >
      prefect worker start --pool default-agent-pool
    volumes:
      - .:/app

volumes:
  prefect_pg_data:
