services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - "5050"
    environment:
      - FLASK_ENV=production

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # Expose Nginx to host
    depends_on:
      - flask  # Ensure Flask starts before Nginx
