services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    command: >
      mlflow server
      --backend-store-uri /mlflow/mlruns
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000