global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/alert_rules/*.yml"

scrape_configs:
  - job_name: "monitoring"
    metrics_path: /metrics
    static_configs:
      - targets: ["monitoring:8000"]
