FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

ENV PYTHONPATH=/app

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

CMD ["prefect", "worker", "start", "--pool", "default-agent-pool"]

