services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    command: >
      mlflow server
      --backend-store-uri /mlflow/mlruns
      --default-artifact-root /mlflow/mlruns
      --host 0.0.0.0
      --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns