experiment_name: "music_genre_tf"
registered_model_name: "music_genre_tf_model"

training:
  l2_reg:       0.01
  epochs:       15
  batch_size:   32
  patience:     5
  learning_rate: 0.0001

paths:
  data:        "data_10.npz"
  output_dir:  "../flask"
  model_name:  "model.keras"